name: Ready the code and deploy the app

on: [push, workflow_dispatch]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory
        run: |
          pwd
          ls -la
          echo $GITHUB_WORKSPACE
